### ISSUE TITLE
TENGO UN PROBLEMA CON SUS CARAS 

### ISSUE THREAD

**Issue by Rinava** [Gexygamma/NET_TP2#1]
_NO_ PUEDE SER QUE NO ME AGREGUEN 

ME PONE SAD
NO PUEDE SER QUE SIEMPRE AMEGUEN
ME PONE MAD

CACHUCHA MI LUCHA
ME SIENTO EN LA DUCHA
CACHUCHA QUE DICHA
LA VIEJA SE DESPINCHA

QUE GRANDE TU OSADÍA
ALEJARME DE MI AGONÍA

> ME PICA EL CULO

ME SIENTO RE MULO__

@Gexygamma @Nicolas-Ales #

**Comment by Gexygamma** [comment]
Arreglado en la próxima versión.
